insert into Klinika values ('1','Modré nebe','Nebeská 1245','Praha')
insert into Klinika values ('2','Dr. Plastik','Èeská 2416','Litomìøice')
insert into Klinika values ('3','Plastika Novák','Pøíèná 81','Litomìøice')
insert into Klinika values ('4','Zelená zem','Stavbaøù 128','Praha')
insert into Klinika values ('5','Plastika Novák','Pøíkrá 1514','Brno')
insert into Klinika values ('6','Klíè ke kráse','Rùová 891','Ostrava')
insert into Klinika values ('7','Dokonalost sama','Hájkova 615','Liberec')
insert into Klinika values ('8','Plastika Martínek','Na Vısluní 54','Ústí nad Labem')
insert into Klinika values ('9','Plastika U Špalíkù','Èeradická','Dìèín')
insert into Klinika values ('10','U sv. Petra','Husova 513','Brno')
insert into Klinika values ('11','Ráj na zemi','Jungmannova 618','Jablonec nad Nisou')
insert into Klinika values ('12','Aranka','Arbesova','Louny')

insert into Doktor values ('1','Josef','Novák','1','746311354')
insert into Doktor values ('2','Martin','Menšík','2','562100838')
insert into Doktor values ('3','Lukáš','Novotnı','3','730358503')
insert into Doktor values ('4','Jan','Øimnáè','4','464461128')
insert into Doktor values ('5','Vojtìch','Pospíšil','5','732015952')
insert into Doktor values ('6','Vojtìch','Mariniè','6','603200908')
insert into Doktor values ('7','Natálie','Martínková','7','494171308')
insert into Doktor values ('8','Daniel','Krejèí','8','606748552')
insert into Doktor values ('9','Nikola','Svrèinová','9','451213112')
insert into Doktor values ('10','Aneta','Skuhrová','10','325152151')
insert into Doktor values ('11','Lukáš','Masopust','11','951511684')
insert into Doktor values ('12','Matìj','Sekret','12','551215474')
insert into Doktor values ('13','David','Klán','1','155234813')
insert into Doktor values ('14','Patrik','Dokoupil','1','612612846')
insert into Doktor values ('15','Ondøej','Navrátil','4','651435843')
insert into Doktor values ('16','Jaroslav','Bìlina','5','843218324')
insert into Doktor values ('17','Marek','Honc','8','851135151')
insert into Doktor values ('18','Barbora','Havránková','10','618121845')
insert into Doktor values ('19','Lucie','Schovancová','3','489318516')

insert into Zdravotni_Pojistovna values ('111','Všeobecná zdravotní pojišovna')
insert into Zdravotni_Pojistovna values ('222','Vojenská zdravotní pojištovna')
insert into Zdravotni_Pojistovna values ('333','Národní zdravotní pojištovna')
insert into Zdravotni_Pojistovna values ('444','Evropská zdravotní pojišovna')
insert into Zdravotni_Pojistovna values ('555','Zdravotní pojišovna pro rodinu')
insert into Zdravotni_Pojistovna values ('666','Zdravotní pojišovna Liška')
insert into Zdravotni_Pojistovna values ('777','Èeská zdravotní pojišovna')
insert into Zdravotni_Pojistovna values ('888','Bratrská zdravotní pojišovna')
insert into Zdravotni_Pojistovna values ('999','Nejlevnìjší zdravotní pojišovna')
insert into Zdravotni_Pojistovna values ('123','Základní zdravotní pojišovna')

insert into Procedura values ('1','Zmenšení prsou','2000')
insert into Procedura values ('2','Zvìtšení prsou','5000')
insert into Procedura values ('3','Zvìtšení nosu','10000')
insert into Procedura values ('4','Zvìtšení rtù','6750')
insert into Procedura values ('5','Vyhlazení vrásek','8500')
insert into Procedura values ('6','Liposukce bøicha','4000')
insert into Procedura values ('7','Plastická operace uší','35000')
insert into Procedura values ('8','Plastická operace dolních víèek','5000')
insert into Procedura values ('9','Plastická operace horních víèek','8400')
insert into Procedura values ('10','Modelace prsou','9000')

insert into Pacient values ('1','Marek','Siøištì','M','111')
insert into Pacient values ('2','Petr','Skuthan','M','222')
insert into Pacient values ('3','Petr','Kutil','M','333')
insert into Pacient values ('4','Denis','Pazourek','M','444')
insert into Pacient values ('5','Veronika','Endrštová','Z','555')
insert into Pacient values ('6','Jiøí','Belinger','M','666')
insert into Pacient values ('7','Matìj','Kunc','M','777')
insert into Pacient values ('8','Ondøej','Hubálek','M','888')
insert into Pacient values ('9','Michaela','Èerminová','Z','999')
insert into Pacient values ('10','Radek','Haišman','M','111')
insert into Pacient values ('11','Tomáš','Urban','M','222')
insert into Pacient values ('12','Jakub','Petøíèek','M','333')
insert into Pacient values ('13','Filip','Urban','M','222')

